name: recsys2023
channels:
  - conda-forge
dependencies:
  - ipykernel=6.23.1
  - ipython=8.12.0
  - pip=23.1.2
  - python=3.8.16
  - pip:
    - numpy==1.24.3
    - pandas==2.0.2
    - scikit-learn==1.2.2
    - tensorflow==2.9.3
